# Generated by Django 2.0.1 on 2018-02-12 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter the employee's name", max_length=100, verbose_name='Full name')),
                ('int_phone', models.PositiveIntegerField(default=100, help_text='Enter the internal phone number')),
                ('ext_phone', models.CharField(help_text='Enter the external (mobile) phone number', max_length=12)),
                ('job_title', models.CharField(help_text="Enter the employee's job title", max_length=100)),
                ('interaction', models.PositiveIntegerField(default=0, verbose_name='interaction')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_of_user', to='taskmanager.Employee')),
            ],
            options={
                'verbose_name': 'Employee',
                'ordering': ('name',),
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
