# Generated by Django 2.0.1 on 2018-02-14 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, help_text='Enter the Department name', max_length=100, verbose_name='Department name')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_of_department', to='taskmanager.Employee')),
            ],
            options={
                'verbose_name_plural': 'Departments',
                'ordering': ('name',),
                'verbose_name': 'Department',
            },
        ),
    ]
