# Generated by Django 2.0.1 on 2018-02-16 18:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the project name', max_length=120, verbose_name='name')),
                ('color', models.CharField(default='#fff', help_text='Enter the hex color code, like #ccc or #cccccc', max_length=7, validators=[django.core.validators.RegexValidator('(^#[0-9a-fA-F]{3}$)|(^#[0-9a-fA-F]{6}$)')], verbose_name='color')),
                ('description', models.TextField(blank=True, help_text='Enter description', null=True, verbose_name='Description')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Enter the priority of the project', verbose_name='Priority')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='taskmanager.Employee', verbose_name='Project Manager')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ('user', 'name'),
                'verbose_name': 'Project',
            },
        ),
    ]
