# Generated by Django 2.0.1 on 2018-02-17 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0007_auto_20180217_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Enter description', null=True, verbose_name='Description')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date & time')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='taskmanager.Project', verbose_name='project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee', to='taskmanager.Employee', verbose_name='employee')),
            ],
            options={
                'ordering': ('project', 'user'),
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('project', 'user')},
        ),
    ]
