# Generated by Django 2.0.1 on 2018-02-17 12:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0008_auto_20180217_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the project name', max_length=120, verbose_name='name')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Enter the priority of the task', verbose_name='Priority')),
                ('due_date', models.DateField(default=datetime.date.today, help_text='Enter the planned due date', verbose_name='Due date')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='Completed date')),
                ('description', models.TextField(blank=True, help_text='Enter description', null=True, verbose_name='Description')),
                ('parenttask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_task', to='taskmanager.Task', verbose_name='Parent task')),
            ],
            options={
                'ordering': ('priority', 'name'),
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_reason', models.CharField(max_length=64)),
                ('appointer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_appoints', to='taskmanager.Employee')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Employee')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Task')),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('priority', 'name'), 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='taskmanager.Project', verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='taskmanager.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='taskmanager.Project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='task',
            name='resources',
            field=models.ManyToManyField(through='taskmanager.TaskResources', to='taskmanager.Employee'),
        ),
    ]
